
services:
  mongo:
    image: mongo:7
    container_name: cards-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  flask:
    build: .
    container_name: flask-cards-app
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo_data:
